#!/bin/bash

_cli_bash_autocomplete() {
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion
    opts=$(cat ~/.clc/completion | sed 's/ /\\\\ /g')
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _cli_bash_autocomplete clc
