#!/bin/bash

mkdir -p ~/.bash_completion
cp ./autocomplete/bash_autocomplete ~/.bash_completion/clc

source_autocompletion="source ~/.bash_completion/clc"
if [[ $(grep -c "$source_autocompletion" ~/.bash_profile) -eq 0 ]]; then
    echo $source_autocompletion >> ~/.bash_profile
fi

source ~/.bash_completion/clc
