#!/bin/bash

CLC_AUTOCOMPLETION_PATH=~/.bash_completion.d/clc

mkdir -p ~/.bash_completion.d
cp ./autocomplete/bash_autocomplete $CLC_AUTOCOMPLETION_PATH

if [[ $(grep -c "$CLC_AUTOCOMPLETION_PATH" ~/.bash_profile --no-messages) -eq 0 ]]; then
    echo "" >> ~/.bash_profile
    echo "[[ -s $CLC_AUTOCOMPLETION_PATH ]] && source $CLC_AUTOCOMPLETION_PATH" >> ~/.bash_profile
fi

echo "Note: To start using CLC CLI autocompletion you need to reload your shell."
echo "You can do it by login out and in again or by running 'source ~/.bash_profile'"
